CREATE TABLE JOBS(
	ID SERIAL NOT NULL UNIQUE,
	ISIM TEXT NOT NULL,
	ACIKLAMA TEXT NOT NULL,
	POINT INTEGER NOT NULL,
	PARENT INTEGER,
	STATUS INTEGER,
	
	FOREIGN KEY (PARENT) REFERENCES JOBS(ID)
);
CREATE TABLE USERS(
	ID SERIAL NOT NULL UNIQUE,
	ISIM TEXT NOT NULL,
	E_POSTA TEXT NOT NULL UNIQUE,
	SIFRE TEXT NOT NULL,
	POINT INTEGER NOT NULL,
	ADMN INTEGER,
	ACTIVE INTEGER NOT NULL
);
CREATE TABLE MESSAGES(
	ID SERIAL NOT NULL UNIQUE,
	MESAJ TEXT NOT NULL,
	USER_ID INTEGER NOT NULL,
	
	FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);
CREATE TABLE USERS_JOBS(
	ID SERIAL NOT NULL UNIQUE,
	USER_ID INTEGER NOT NULL,
	JOB_ID INTEGER NOT NULL,
	DEADLINE TEXT NOT NULL,
	
	FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
	FOREIGN KEY (JOB_ID) REFERENCES JOBS(ID)
);
CREATE TABLE MESSAGES_JOBS(
	ID SERIAL NOT NULL UNIQUE,
	MESAJ_ID INTEGER NOT NULL,
	JOB_ID INTEGER NOT NULL,
	
	FOREIGN KEY (MESAJ_ID) REFERENCES MESSAGES(ID),
	FOREIGN KEY (JOB_ID) REFERENCES JOBS(ID)
);
CREATE TABLE MESSAGES_USERS(
	ID SERIAL NOT NULL UNIQUE,
	MESAJ_ID INTEGER NOT NULL,
	USER_ID INTEGER NOT NULL,
	
	FOREIGN KEY (MESAJ_ID) REFERENCES MESSAGES(ID),
	FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);
CREATE TABLE LOGS(
	ID SERIAL NOT NULL UNIQUE,
	LOG_RECORD TEXT NOT NULL,
	E_POSTA TEXT NOT NULL,
	DATE_TIME TEXT NOT NULL,
	
	FOREIGN KEY (E_POSTA) REFERENCES USERS(E_POSTA)
);